# -*- coding: utf-8 -*-
"""M,SD,V.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1T9nOdkBG48GzUC83z_Q8Y6VIkq4KfaNP
"""

import numpy as np
def standard_deviation(datalist):
  mean = np.mean(datalist)
  standardDeviation = np.std(datalist)
  variance = np.var(datalist)
  print('The mean of the datalist is', mean)
  print('The StandardDeviation of the datalist is', standardDeviation)
  print('The Variance of the datalist is', variance)
standard_deviation(datalist =[1,2,3,4,5])

